### ISSUE TITLE
Error in UseMethod("genome.plot") : no applicable method for 'genome.plot' applied to an object of class "arrayCGH"

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/MANOR#1]
Error in version 1.59.1 From http://bioconductor.org/checkResults/devel/bioc-LATEST/MANOR/tokay2-buildsrc.html:

```
Error: processing vignette 'MANOR.Rnw' failed with diagnostics:
 chunk 16 
Error in UseMethod("genome.plot") : 
  no applicable method for 'genome.plot' applied to an object of class "arrayCGH"

--- failed re-building 'MANOR.Rnw'

SUMMARY: processing the following file failed:
  'MANOR.Rnw'

Error: Vignette re-building failed.
Execution halted
```

Looks like a NAMESPACE issue to me.

Note that this issue may not exist anymore already: as of version 1.59.2 I added 

```
S3method(genome.plot, arrayCGH)
S3method(genome.plot, default)
```

to the package NAMESPACE. Also, the vignette has been converted to a .Rmd vignette.

**Comment by HenrikBengtsson** [comment]
Yes, registering the S3 method that way should fix this problem.

**Comment by HenrikBengtsson** [comment]
I've added CI testing and "modernized" this package/repos a bit.  I think you solved the original problem yourself.  The version on the `master` branch is read to be pushed to Bioconductor devel.

**Comment by HenrikBengtsson** [comment]
I see that MANOR 1.59.**3** just hit Bioc and solved this problem.  Closing.  I'll create another issue for syncing this repos with what's on Bioc devel.
